# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a3d89f01-0e8f-4fd4-80ef-e977185cff60";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/95B1-85C2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware = {
    nvidia = {
      nvidiaPersistenced = true;
      open = false;
      prime = {
        # allowExternalGpu = false;
	      sync.enable = true;
	      #reverseSync.enable = true;
	      #offload = {
	      #  enable = true;
	      #  enableOffloadCmd = true;
	      #};
	      nvidiaBusId = "PCI:1:0:0";
	      amdgpuBusId = "PCI:7:0:0";
	    };
	    powerManagement = {
	      enable = true;
		    # finegrained = true;
      };
      package = lib.mkForce config.boot.kernelPackages.nvidiaPackages.beta;
      modesetting.enable = true;
      nvidiaSettings = false;
    };
  };
}
